version: "3.9"
services:
  client-react-ngnix:
    labels:
      shipyard.primary-route: true
      shipyard.route: "/"
    image: client-react-nginx:1.1
    build:
      context: ./React-Client
      dockerfile: ./Dockerfile
    init: true
    ports:
      - 80:8080
    networks:
      - frontend
    restart: unless-stopped
  api-golang:
    labels:
      shipyard.primary-route: true
      shipyard.route: "/api/golang"
    init: true
    image: api-golang:1.1
    build:
      context: ./Go-Application
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:adityaspostgres@db:5432/dockerPractice
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend
    restart: unless-stopped
  api-node:
    labels:
      shipyard.primary.route: true
      shipyard.route: "/api/node"
    image: api-node:1.1
    init: true
    build:
      context: ./Node-Application
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:adityaspostgres@db:5432/dockerPractice
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
  db:
    image: postgres:15.4-alpine3.18
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=adityaspostgres
      - POSTGRES_DB=dockerPractice
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  frontend:
  backend:
