version: "3.9"
services:
  client-react-ngnix:
    image: client-react-nginx-dev
    build:
      context: ./React-Client
      dockerfile: ./Dockerfile
    init: true
    ports:
      - 80:8080
    networks:
      - frontend
    restart: unless-stopped
  api-golang:
    image: api-golang-dev
    build:
      context: ./Go-Application
      dockerfile: ./Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./Go-Application
        target: /app/
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:adityaspostgres@db:5432/dockerPractice
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend
    restart: unless-stopped
  api-node:
    image: api-node-dev
    build:
      context: ./Node-Application
      dockerfile: ./Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./Node-Application
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:adityaspostgres@db:5432/dockerPractice
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
  db:
    image: postgres:15.4-alpine3.18
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=adityaspostgres
      - POSTGRES_DB=dockerPractice
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  frontend:
  backend:
